# -*- coding: utf-8 -*-
"""EJERCICIOSCLASE2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zzh4yLxxySx1Ta-4SzXNes7i07l5-F7n

1-	Escribir un programa que pregunte el nombre del usuario en la consola y después de que el usuario lo introduzca muestre por pantalla la cadena ¡Hola <nombre>!, donde <nombre> es el nombre que el usuario haya introducido.
"""

valor1 = (input("Escriba su nombre:"))

print("Hola!" , valor1)

"""Escribir un programa que muestre por pantalla el resultado de la siguiente operación aritmética ((3+2)/(2*5))^2"""

Calculo1=((3+2)/(2*5))**2
print ("El resultado del Calculo es:", Calculo1)

"""3-	Escribir un programa que pregunte al usuario por el número de horas trabajadas y el coste por hora. Después debe mostrar por pantalla la paga que le corresponde."""

valor1 = int(input("Ingrese número de horas trabajadas:"))
valor2 = int(input("Ingrese el coste por hora:"))

calculo1=valor1*valor2


print("Su pago es de: $" ,calculo1)

"""4-	Escribir un programa que lea un entero positivo n, introducido por el usuario y después muestre en pantalla la suma de todos los enteros desde 1 hasta n. La suma de los n primeros enteros positivos puede ser calculada de la siguiente forma: suma=n((n+1)/2)"""

n = int(input("Ingrese un numero entero positivo:"))

suma=n*(n+1)/2


print("La suma de los primeros números enteros desde 1 hasta " + str(n) + " es " + str(suma))

"""5-	Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, y muestre por pantalla la frase Tu índice de masa corporal es <imc> donde <imc> es el índice de masa corporal calculado redondeado con dos decimales. round(numero, 2) """

peso = input("Ingrese su peso en kg:")
estatura = input("Ingrese su estatura en metros:")

imc=round(float(peso)/float(estatura)**2,2)


print("Tu índice de masa corporal es:" +  str(imc))

"""6-	Una juguetería tiene mucho éxito en dos de sus productos: payasos y muñecas. Suele hacer venta por correo y la empresa de logística les cobra por peso de cada paquete así que deben calcular el peso de los payasos y muñecas que saldrán en cada paquete a demanda. Cada payaso pesa 112 g y cada muñeca 75 g. Escribir un programa que lea el número de payasos y muñecas vendidos en el último pedido y calcule el peso total del paquete que será enviado."""

peso_payaso = 112
peso_muñeca = 75

payasos = int(input("Ingrese el numero de payasos vendidos:"))
muñecas = int(input("Ingrese el numero de muñecas vendidos:"))

peso_total = peso_payaso * payasos + peso_muñeca * muñecas


print("El peso total del paquete es:"+str(peso_total))

"""7-	Una panadería vende barras de pan a 35$ cada una. El pan que no es el día tiene un descuento del 60%. Escribir un programa que comience leyendo el número de barras vendidas que no son del día. Después el programa debe mostrar el precio habitual de una barra de pan, el descuento que se le hace por no ser fresca y el coste final total.
Ejemplo:
Precio del pan:
Descuento:
Precio del pan con descuento incluido: 

"""

precio_barras= 35
descuento_pan_viejo = 60
barras_pan_vendidas= int(input("Ingrese el numero de barras vendidas que no son del dia:"))

descuento= float(descuento_pan_viejo*precio_barras)/100

print("Precio del pan: $" + str(precio_barras) + " Descuento: $" + str(descuento) + " Precio del pan con descuento incluido: $" + str(precio_barras-descuento))